---
title: "Untitled"
author: "Giacomo De Gobbi"
date: "7/25/2021"
output: html_document
---



```{r}
library(tidyverse)
library(httr)


headers = c(
  `Connection` = 'keep-alive',
  `Accept` = 'application/json, text/plain, */*',
  `x-nba-stats-token` = 'true',
  `X-NewRelic-ID` = 'VQECWF5UChAHUlNTBwgBVw==',
  `User-Agent` = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
  `x-nba-stats-origin` = 'stats',
  `Sec-Fetch-Site` = 'same-origin',
  `Sec-Fetch-Mode` = 'cors',
  `Referer` = 'https://stats.nba.com/players/leaguedashplayerbiostats/',
  `Accept-Encoding` = 'gzip, deflate, br',
  `Accept-Language` = 'en-US,en;q=0.9'
)

```
```{r}
url= "https://stats.nba.com/stats/videodetailsasset?AheadBehind=&CFID=&CFPARAMS=&ClutchTime=&Conference=&ContextFilter=&ContextMeasure=FGA&DateFrom=&DateTo=&Division=&EndPeriod=0&EndRange=28800&GROUP_ID=&GameEventID=&GameID=0042000406&GameSegment=&GroupID=&GroupMode=&GroupQuantity=5&LastNGames=0&LeagueID=00&Location=&Month=0&OnOff=&OpponentTeamID=0&Outcome=&PORound=0&Period=0&PlayerID=203507&PlayerID1=&PlayerID2=&PlayerID3=&PlayerID4=&PlayerID5=&PlayerPosition=&PointDiff=&Position=&RangeType=0&RookieYear=&Season=2020-21&SeasonSegment=&SeasonType=Playoffs&ShotClockRange=&StartPeriod=0&StartRange=0&StarterBench=&TeamID=1610612749&VsConference=&VsDivision=&VsPlayerID1=&VsPlayerID2=&VsPlayerID3=&VsPlayerID4=&VsPlayerID5=&VsTeamID="
```

```{r}
res <- httr::GET(url = url, httr::add_headers(.headers=headers))
json_resp <- jsonlite::fromJSON(content(res, "text"))
df <- data.frame(json_resp$resultSets$rowSet[1])
colnames(df) <- json_resp[["resultSets"]][["headers"]][[1]]
```

```{r}
View(df)
```

```{r}
library(readr)

write_csv(df, "/Users/Giacomo/Desktop/ProgettoDataMan/ant34.csv")
```




```{r}
df$LOC_X <- as.numeric(as.character(df$LOC_X))
df$LOC_Y <- as.numeric(as.character(df$LOC_Y))

df %>% 
  ggplot(aes(x = LOC_X, y = LOC_Y)) + 
  geom_point() +
  coord_equal()
```
```{r}

library(shiny)
runGitHub("ballr", "toddwschneider")
```






